/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sudoku;
import java.awt.Component;
import javax.swing.*;
import java.awt.Color;
import javax.swing.border.Border;

/**
 *
 * @author prashant
 */
public class Easy_Game extends javax.swing.JFrame {

    /**
     * Creates new form Easy_Game
     */
    public Easy_Game() {
                n = 6;
		k = 20;
		mat = new int[n][n];
        initComponents();
        jLabel1.setText("Welcome " + pop);
    }
    public  Easy_Game(String Om){
                n = 6;
		k = 20;
		mat = new int[n][n];

        pop = Om;
        initComponents();
        jLabel1.setText("Welcome " + pop);
    }
    String pop;
    JFrame frame = new JFrame();
    int n,k;
    int[] mat[];
    
    public void fillValue() {
		for(int i = 0;i < 4;i = i + 2) {
                    if(i == 0){
			fillBox(i,i);
                    }
                    else{
                        fillBox(i,i+1);
                    }
		}
               
		fillRemaining(0,3);
		removeKDigits();		
		}

	boolean unUsedInBox(int rowstart,int colstart,int num) {		//rreturn false if given 3*3 box contains num
		for(int i = 0;i<2;i++) {
			for(int j = 0;j<3;j++) {
				if(mat[rowstart + i][colstart + j] == num) {
					return false;
					}
				}
			}
		return true;
		}

	void fillBox(int row,int col) {
		int num;
		for(int i = 0;i<2;i++){
			for(int j = 0;j<3;j++) {
				do {
					num = (int) Math.floor((Math.random()*n+1));
				}
				while(!unUsedInBox(row,col,num));
				mat[row + i][col + j] = num;
				}
			}
		}

	boolean checkIfSafe(int r,int c,int num) {
		for(int k = 0;k < n;k++) {
			if(mat[r][k] == num) {
				return false;
				}
			if(mat[k][c] == num) {
				return false;
				}
		}
		int rowstart = r - r%2;
		int colstart = c - c%3;
		for(int i = 0;i<2;i++) {
			for(int j = 0;j<3;j++) {
				if(mat[rowstart + i][colstart + j] == num) {
					return false;
					}
				}
			}
			
		return true;
		}
	
	boolean fillRemaining(int r,int c) {  
	if (c>=n && r<n-1) { // j>=9 && i < 8
            r = r + 1; 
            c = 0; 
        } 
        if (r>=n-1 && c>=n) // i >= 9 && j >= 9
            return true; 
        

        if (r < 2 && c < 3) { 	// i < 3 it is to skip the first diagonal 3x3 matrix
             c = 3;// j < 3
        } 
        else if (r < n-2 && c > 2 && r > 1)  { 	// i < 6  it is to skip the second diagonal 3x3
                r = r + 1; // j == 3
                c =  0; 	//  j =  6
        } 

        for (int num = 1; num<=n; num++)  { 
            if (checkIfSafe(r, c, num))   { 
                mat[r][c] = num; 
                if (fillRemaining(r, c+1)) { 
                    return true;  }
                mat[r][c] = 0; 
            } 
        } 
        return false; 
     } 

	private void removeKDigits() {
		int count = k;
		while(count != 0) {
			int cellID = (int) Math.floor((Math.random()*(n*n)+1));
			int i = (cellID/n); 
           	int j = cellID%n; 
         	if(i != n){
         		if (mat[i][j] != 0) {
           	     count--; 
           		 mat[i][j] = 0; 
          		  }
          	 } 
	 	 }
	}
        public void reset() {
           for(int i = 0;i < n;i++){
               for(int j = 0;j < n;j++){
                   mat[i][j] = 0;
               }
           }
           
           fillValue();
           
        }
    
    static int milisecond = 0;
    static int second = 0;
    static int minute = 0;
    static boolean state = true;
    int change = 1;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jTextField32 = new javax.swing.JTextField();
        jTextField33 = new javax.swing.JTextField();
        jTextField34 = new javax.swing.JTextField();
        jTextField35 = new javax.swing.JTextField();
        jTextField36 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLMain = new javax.swing.JLabel();
        jLTime1 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        sec = new javax.swing.JLabel();
        min = new javax.swing.JLabel();
        milisec = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sudoku for beginners");
        setResizable(false);

        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel2.setPreferredSize(new java.awt.Dimension(600, 600));
        jPanel2.setLayout(new java.awt.GridLayout(6, 6, 3, 0));

        jTextField1.setBackground(new java.awt.Color(255, 0, 102));
        jTextField1.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setToolTipText("");
        jPanel2.add(jTextField1);

        jTextField2.setBackground(new java.awt.Color(255, 0, 102));
        jTextField2.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setToolTipText("");
        jPanel2.add(jTextField2);

        jTextField3.setBackground(new java.awt.Color(255, 0, 102));
        jTextField3.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setToolTipText("");
        jPanel2.add(jTextField3);

        jTextField4.setBackground(new java.awt.Color(0, 153, 153));
        jTextField4.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setToolTipText("");
        jPanel2.add(jTextField4);

        jTextField5.setBackground(new java.awt.Color(0, 153, 153));
        jTextField5.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setToolTipText("");
        jPanel2.add(jTextField5);

        jTextField6.setBackground(new java.awt.Color(0, 153, 153));
        jTextField6.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setToolTipText("");
        jPanel2.add(jTextField6);

        jTextField7.setBackground(new java.awt.Color(255, 0, 102));
        jTextField7.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.setToolTipText("");
        jPanel2.add(jTextField7);

        jTextField8.setBackground(new java.awt.Color(255, 0, 102));
        jTextField8.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField8.setToolTipText("");
        jPanel2.add(jTextField8);

        jTextField9.setBackground(new java.awt.Color(255, 0, 102));
        jTextField9.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField9.setToolTipText("");
        jPanel2.add(jTextField9);

        jTextField10.setBackground(new java.awt.Color(0, 153, 153));
        jTextField10.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField10.setToolTipText("");
        jPanel2.add(jTextField10);

        jTextField11.setBackground(new java.awt.Color(0, 153, 153));
        jTextField11.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        jTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField11.setToolTipText("");
        jPanel2.add(jTextField11);

        jTextField12.setBackground(new java.awt.Color(0, 153, 153));
        jTextField12.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        jTextField12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField12.setToolTipText("");
        jPanel2.add(jTextField12);

        jTextField13.setBackground(new java.awt.Color(204, 204, 0));
        jTextField13.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        jTextField13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField13.setToolTipText("");
        jPanel2.add(jTextField13);

        jTextField14.setBackground(new java.awt.Color(204, 204, 0));
        jTextField14.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        jTextField14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField14.setToolTipText("");
        jPanel2.add(jTextField14);

        jTextField15.setBackground(new java.awt.Color(204, 204, 0));
        jTextField15.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        jTextField15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField15.setToolTipText("");
        jPanel2.add(jTextField15);

        jTextField16.setBackground(new java.awt.Color(51, 204, 0));
        jTextField16.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        jTextField16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField16.setToolTipText("");
        jPanel2.add(jTextField16);

        jTextField17.setBackground(new java.awt.Color(51, 204, 0));
        jTextField17.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        jTextField17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField17.setToolTipText("");
        jPanel2.add(jTextField17);

        jTextField18.setBackground(new java.awt.Color(51, 204, 0));
        jTextField18.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        jTextField18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField18.setToolTipText("");
        jPanel2.add(jTextField18);

        jTextField19.setBackground(new java.awt.Color(204, 204, 0));
        jTextField19.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        jTextField19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField19.setToolTipText("");
        jPanel2.add(jTextField19);

        jTextField20.setBackground(new java.awt.Color(204, 204, 0));
        jTextField20.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        jTextField20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField20.setToolTipText("");
        jPanel2.add(jTextField20);

        jTextField21.setBackground(new java.awt.Color(204, 204, 0));
        jTextField21.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        jTextField21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField21.setToolTipText("");
        jPanel2.add(jTextField21);

        jTextField22.setBackground(new java.awt.Color(51, 204, 0));
        jTextField22.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        jTextField22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField22.setToolTipText("");
        jPanel2.add(jTextField22);

        jTextField23.setBackground(new java.awt.Color(51, 204, 0));
        jTextField23.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        jTextField23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField23.setToolTipText("");
        jPanel2.add(jTextField23);

        jTextField24.setBackground(new java.awt.Color(51, 204, 0));
        jTextField24.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        jTextField24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField24.setToolTipText("");
        jPanel2.add(jTextField24);

        jTextField25.setBackground(new java.awt.Color(0, 204, 204));
        jTextField25.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        jTextField25.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField25.setToolTipText("");
        jPanel2.add(jTextField25);

        jTextField26.setBackground(new java.awt.Color(0, 204, 204));
        jTextField26.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        jTextField26.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField26.setToolTipText("");
        jPanel2.add(jTextField26);

        jTextField27.setBackground(new java.awt.Color(0, 204, 204));
        jTextField27.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        jTextField27.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField27.setToolTipText("");
        jPanel2.add(jTextField27);

        jTextField28.setBackground(new java.awt.Color(255, 51, 51));
        jTextField28.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        jTextField28.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField28.setToolTipText("");
        jPanel2.add(jTextField28);

        jTextField29.setBackground(new java.awt.Color(255, 51, 51));
        jTextField29.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        jTextField29.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField29.setToolTipText("");
        jPanel2.add(jTextField29);

        jTextField30.setBackground(new java.awt.Color(255, 51, 51));
        jTextField30.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        jTextField30.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField30.setToolTipText("");
        jPanel2.add(jTextField30);

        jTextField31.setBackground(new java.awt.Color(0, 204, 204));
        jTextField31.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        jTextField31.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField31.setToolTipText("");
        jPanel2.add(jTextField31);

        jTextField32.setBackground(new java.awt.Color(0, 204, 204));
        jTextField32.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        jTextField32.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField32.setToolTipText("");
        jPanel2.add(jTextField32);

        jTextField33.setBackground(new java.awt.Color(0, 204, 204));
        jTextField33.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        jTextField33.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField33.setToolTipText("");
        jPanel2.add(jTextField33);

        jTextField34.setBackground(new java.awt.Color(255, 51, 51));
        jTextField34.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        jTextField34.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField34.setToolTipText("");
        jPanel2.add(jTextField34);

        jTextField35.setBackground(new java.awt.Color(255, 51, 51));
        jTextField35.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        jTextField35.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField35.setToolTipText("");
        jPanel2.add(jTextField35);

        jTextField36.setBackground(new java.awt.Color(255, 51, 51));
        jTextField36.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        jTextField36.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField36.setToolTipText("");
        jPanel2.add(jTextField36);

        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Menu");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("About");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton6.setText("Play");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLMain.setIcon(new javax.swing.ImageIcon("/home/prashant/NetBeansProjects/Sudoku/sudoku.png")); // NOI18N

        jLTime1.setFont(new java.awt.Font("DejaVu Sans", 0, 36)); // NOI18N
        jLTime1.setText("Time:");

        jButton7.setText("Wanna try diagonal or xsudoku");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        sec.setFont(new java.awt.Font("DejaVu Sans", 0, 36)); // NOI18N
        sec.setText("00");
        sec.setToolTipText("");

        min.setFont(new java.awt.Font("DejaVu Sans", 0, 36)); // NOI18N
        min.setText("00:");
        min.setToolTipText("");

        milisec.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        milisec.setText("000");
        milisec.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLTime1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(min)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sec)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(milisec, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(64, 64, 64))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(209, 209, 209)))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLMain, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(390, 390, 390))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLMain, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLTime1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(min, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sec, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(milisec, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(86, 86, 86)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JFrame frame2 = new JFrame();
       if(JOptionPane.showConfirmDialog(frame2,"Direct you to Menu \nNote: Progress in this game will lost","wait wait wait!!!",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
        dispose();
        Home home = new Home();
        home.setVisible(true);
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       if(JOptionPane.showConfirmDialog(frame,"confirm if you wanna to exit","wait wait wait!!!",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
           System.exit(0);
       }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int i =0,j =0;
       state = true;
      
       if("Play".equals(jButton6.getText())){
           if(change == 1){
               reset();
           JTextField temp  = null;
        for(Component c:jPanel2.getComponents()){
                if(c.getClass().toString().contains("javax.swing.JTextField")){
                      temp=(JTextField)c;
                      temp.setColumns(1);
                      if(mat[i][j] != 0){
                      temp.setText(Integer.toString(mat[i][j]));
                      temp.setEditable(false);
                      }
                      else {
                        temp.setEditable(true);
                        temp.setText("");
                      }
                      temp.setVisible(true);
                      j++;
                      if(j == 6){
                          j = 0;
                          i++;
                      }
                      if( i == 6){
                          break;
                      }
                 }
              } 
                     change = 0;
                    jButton6.setText("Pause");
           }
           else{
                JTextField temp = null;
        for(Component c:jPanel2.getComponents()){
            if(c.getClass().toString().contains("javax.swing.JTextField")) {
                temp = (JTextField)c;
                temp.setVisible(true);
                
                 }
              }
              jButton6.setText("Pause");
           }
           state = true;
           Thread th = new Thread(){
               public void run() {
                   for(;;){
                       if(state == true){
                           try{
                               sleep(1);
                               if(milisecond > 1000){
                                   milisecond = 0;
                                   second++;
                               }
                               if(second%5 == 0){
                                    JTextField temp = null;
                                    for(Component c:jPanel2.getComponents()){
                                           if(c.getClass().toString().contains("javax.swing.JTextField")) {
                                                 temp = (JTextField)c;
                                                 temp.setBorder(null);
                
                                              }
                                       }
                               } 
                               
                               if(second >60){
                                   milisecond = 0;
                                   second = 0;
                                   minute++;
                               }
                               if(minute > 60)  {
                                   break;
                               }
                               milisecond++;
                               milisec.setText("" + milisecond);
                               sec.setText(" : " + second);
                               min.setText("" + minute);
                           }
                           catch(InterruptedException ex) {
                               
                           }
                       }
                       else{
                           break;
                       }
                   }
               }
           };
           th.start();
           jLabel1.setText("Ok " + pop);
       }
       else{
           JTextField temp = null;
        for(Component c:jPanel2.getComponents()){
            if(c.getClass().toString().contains("javax.swing.JTextField")) {
                temp = (JTextField)c;
                temp.setVisible(false);
                temp.setBorder(null);
            }
        }
        jButton6.setText("Play");
        jLabel1.setText("Game Paused");
        state = false;
      }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       JTextField temp  = null;
        int[][] solved = new int[n][n];
        int i = 0,j = 0;
        boolean check = false;
        Border border = BorderFactory.createLineBorder(Color.red, 3);
        
        
        for(Component c:jPanel2.getComponents()){
                if(c.getClass().toString().contains("javax.swing.JTextField")){
                      temp=(JTextField)c;
                      if((temp.getText().length() > 1)||(temp.getText().isBlank())||(isNumeric(temp.getText()) == false)) {
                          temp.setBorder(border);
                          check = false;
                      }
                      else  {
                          temp.setBorder(null);
                          solved[i][j] = Integer.valueOf(temp.getText());
                       j++;
                      if(j == 6){
                          j = 0;
                          i++;
                      }
                      if( i == 6){
                          break;
                      } 
                      check = true;
                    }
                 }
            }
        int sum_r = 0,sum_c = 0,sum_s = 0;
        int m,l;
        boolean checkr = false,checkc = false,checks = false;
        if(check == true){
            for(i = 0;i < n;i++){
                sum_r = 0;
                sum_c = 0;
                for(j = 0;j < n;j++){
                    sum_r = sum_r + solved[i][j];
                    sum_c = sum_c + solved[j][i];
                }
                checkr = sum_r == 21; //   break;
                checkc = sum_c == 21;
            }
           for(i = 0;i<n;i = i+3){
               for(j = 0;j<n ;j = j+2){
                   for(m = i;m < (i+3);m++){
                       for(l = j;m < (j+2);m++){
                           sum_s = sum_s + solved[m][l];
                       }
                   }
                   checks = sum_s == 21; //  break;
                   sum_s = 0;
               }
           } 
          if(checkr && checkc && checkc) {
              jLabel1.setText("Congratulations " + pop);
          }
          else{
              jLabel1.setText(pop + ",Try again");
          }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         JTextField temp = null;
        JFrame frame1 =  new JFrame();
        if(JOptionPane.showConfirmDialog(frame1,"After Reset,your progress in this game will lost.\nPress Yes if you want a new Game","Wait Wait Wait!!!"
                ,JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
        reset();
        int i = 0,j = 0;
        for(Component c:jPanel2.getComponents()){
                if(c.getClass().toString().contains("javax.swing.JTextField")){
                      temp=(JTextField)c;
                      temp.setColumns(1);
                      temp.setBorder(null);
                      if(mat[i][j] != 0){
                      temp.setText(Integer.toString(mat[i][j]));
                      temp.setEditable(false);
                      }
                      else {
                        temp.setEditable(true);
                        temp.setText("");
                      }
                      temp.setVisible(true);
                      j++;
                      if(j == 6){
                          j = 0;
                          i++;
                      }
                      if( i == 6){
                          break;
                      }
                 }
            }
        jLabel1.setText("OK " + pop);
        jButton6.setText("Pause");
        milisecond = 0;
        second = 0;
        minute = 0;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        About about = new About();
        about.setVisible(true);
        state = false;
        jButton6.setText("Play");
        JTextField temp = null;
        for(Component c:jPanel2.getComponents()){
                if(c.getClass().toString().contains("javax.swing.JTextField")){
                      temp=(JTextField)c;
                      temp.setVisible(false);
                }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        JFrame frame3= new JFrame();
       if(JOptionPane.showConfirmDialog(frame3,"Direct you to Diagonal Sudoku \nNote: Progress in this game will lost","wait wait wait!!!",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
        dispose();
        xsudoku xs = new xsudoku(pop);
        xs.setVisible(true);
    } 
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Easy_Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Easy_Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Easy_Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Easy_Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Easy_Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLMain;
    private javax.swing.JLabel jLTime1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel milisec;
    private javax.swing.JLabel min;
    private javax.swing.JLabel sec;
    // End of variables declaration//GEN-END:variables
private boolean isNumeric(String s) {
        return java.util.regex.Pattern.matches("\\d+", s);
    }
}
